In [0]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [3]:
torch.manual_seed(1)

In [0]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])

In [5]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [6]:
print(y_train)
print(y_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [7]:
W = torch.zeros(1, requires_grad=True)
print(W)

tensor([0.], requires_grad=True)


In [8]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


# Hypothesis

In [9]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


# Cost

In [10]:
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(4.6667, grad_fn=<MeanBackward0>)


# Gradient Descent

In [11]:
optimizer = optim.SGD([W, b], lr = 0.01)
print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.01
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [0]:
optimizer.zero_grad()
cost.backward()
optimizer.step()

In [13]:
print(W)
print(b)

tensor([0.0933], requires_grad=True)
tensor([0.0400], requires_grad=True)


In [14]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.1333],
        [0.2267],
        [0.3200]], grad_fn=<AddBackward0>)


In [15]:
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(3.6927, grad_fn=<MeanBackward0>)


# Training with Full Code

In [17]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr = 0.01)
# 학습 횟수
nb_epochs = 1000
for epoch in range(nb_epochs + 1):
  hypothesis = x_train * W + b

  cost = torch.mean((hypothesis - y_train) ** 2)
  
  # cost로 H(x) 개선
  optimizer.zero_grad() # gradient를 0으로 초기화
  cost.backward() # gradient 계산
  optimizer.step() # gradient decsent

  if epoch % 100 == 0:
    print("Epock {:4d}/{} W : {:.3f}, b{:.3f}, cost : {:.6f}".format(epoch, nb_epochs, W.item(), b.item(), cost.item()))

Epock    0/1000 W : 0.093, b0.040, cost : 4.666667
Epock  100/1000 W : 0.873, b0.289, cost : 0.012043
Epock  200/1000 W : 0.900, b0.227, cost : 0.007442
Epock  300/1000 W : 0.921, b0.179, cost : 0.004598
Epock  400/1000 W : 0.938, b0.140, cost : 0.002842
Epock  500/1000 W : 0.951, b0.110, cost : 0.001756
Epock  600/1000 W : 0.962, b0.087, cost : 0.001085
Epock  700/1000 W : 0.970, b0.068, cost : 0.000670
Epock  800/1000 W : 0.976, b0.054, cost : 0.000414
Epock  900/1000 W : 0.981, b0.042, cost : 0.000256
Epock 1000/1000 W : 0.985, b0.033, cost : 0.000158


# Multivariable Linear regression

In [0]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [0]:
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(1, 1)
  
  def forward(self, x):
    return self.linear(x)

In [0]:
class MultivariateLinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(3, 1)

  def forward(self, x):
    return self.linear(x)

In [24]:
model = MultivariateLinearRegressionModel()

optimizer = optim.SGD(model.parameters(), lr = 1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
  prediction = model(x_train)
  cost = F.mse_loss(prediction, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  print("Epoch {:4d}/{} Cost : {:.6f}".format(epoch, nb_epochs, cost.item()))

Epoch    0/20 Cost : 31362.457031
Epoch    1/20 Cost : 9830.649414
Epoch    2/20 Cost : 3081.570801
Epoch    3/20 Cost : 966.092896
Epoch    4/20 Cost : 303.002594
Epoch    5/20 Cost : 95.159134
Epoch    6/20 Cost : 30.011412
Epoch    7/20 Cost : 9.590993
Epoch    8/20 Cost : 3.190278
Epoch    9/20 Cost : 1.183925
Epoch   10/20 Cost : 0.555076
Epoch   11/20 Cost : 0.357949
Epoch   12/20 Cost : 0.296167
Epoch   13/20 Cost : 0.276782
Epoch   14/20 Cost : 0.270711
Epoch   15/20 Cost : 0.268800
Epoch   16/20 Cost : 0.268205
Epoch   17/20 Cost : 0.268014
Epoch   18/20 Cost : 0.267945
Epoch   19/20 Cost : 0.267922
Epoch   20/20 Cost : 0.267907
